python3: can't open file '/u': [Errno 2] No such file or directory
PyBot#0310 has connected to Discord!
Check request for sku 81766
Traceback (most recent call last):
  File "./bot.py", line 141, in <module>
    bot.run(TOKEN)
  File "/usr/local/lib/python3.8/dist-packages/discord/client.py", line 715, in run
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/discord/client.py", line 694, in runner
    await self.start(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/discord/client.py", line 657, in start
    await self.login(token)
  File "/usr/local/lib/python3.8/dist-packages/discord/client.py", line 510, in login
    raise TypeError(f"token must be of type str, not {token.__class__.__name__}")
TypeError: token must be of type str, not NoneType
